name: mbaxter tenjava
main: org.kitteh.tenjava.CatPlugin
author: mbaxter
version: '${project.version}'
commands:
  track:
    description: track
  untrack:
    description: untrack
  getid:
    description: getid